### ISSUE TITLE
没法注册啊，万年提示网络担忧

### ISSUE THREAD

**Issue by 1377195627** [slimkit/plus-component-web#102]
没法注册啊，万年提示网络担忧，而且短信也发不出去
![_ _20170727141444](https://user-images.githubusercontent.com/8142265/28656842-c01edf68-7269-11e7-943f-7d4476d8c4e5.png)
![_ _20170727141520](https://user-images.githubusercontent.com/8142265/28656853-d0abc3dc-7269-11e7-8694-8eeb2213f642.png)

![_ _20170727141543](https://user-images.githubusercontent.com/8142265/28656855-d47f4d6c-7269-11e7-9817-1ad30fe44f6c.png)

**Comment by medz** [comment]
你 f12 打开控制台看下请求呢~看错误是啥。

**Comment by 1377195627** [comment]
![image](https://user-images.githubusercontent.com/8142265/28750893-95212a1c-74be-11e7-8c30-e56b48314b6a.png)

**Comment by JsonLeex** [comment]
麻烦你切换到 Network 面板，截图看一下请求的 response

**Comment by 1377195627** [comment]
![image](https://user-images.githubusercontent.com/8142265/28750910-5bc6ad68-74bf-11e7-9f2e-ed2df26700cf.png)

**Comment by 1377195627** [comment]
![image](https://user-images.githubusercontent.com/8142265/28767933-58ddf4ee-759b-11e7-9659-20f568e5d0db.png)
 官方的体验站也有这问题

**Comment by boxshadow** [comment]
拉新代码

**Comment by 1377195627** [comment]
已经是最新的了

**Comment by boxshadow** [comment]
@1377195627 新版发布后会修复 周日下午6点

**Comment by boxshadow** [comment]
@1377195627 拉新包吧
