### ISSUE TITLE
怎么添加icon

### ISSUE THREAD

**Issue by 1459416736** [slimkit/plus-component-web#103]
你好，请问怎么添加一个新icon 组件，我从iconfont 阿里巴巴矢量图标库上下载的svg文件后，在icons 文件下建立了一个vue组件，拷贝了path 始终显示空白？

**Comment by medz** [comment]
熟悉下，你是否 export 了，如果 export 了，你 import 组件后使用是否 你的 svg dom 在页面上？如果在，那么就是你的 svg 代码有误。建议现看一下 svg 相关的只是，再把 icon font 上的图标转为 vue 的组件代码。svg 文件代码并不是直接放进来用的，需要微调。

**Comment by 1459416736** [comment]
你好，我就是你说的把svg 文件代码直接放进来用的；请问怎么做微调下面就是我的代码
``<template>
  <svg class="icon" viewBox="0 0 24 24" :height="height" :width="width" :fill="color" style="display: inherit;" >
  <g><path d="M240.8 650.5c-134.2-237.4-131.3-485.2 6.6-564 29.8-17 64.1-24.8 101.4-23.1 2.8-0.4 5.6-0.7 8.5-0.8 0.2 0 1.5 0 1.7 0 60.7 0 116.2 76.3 129.1 177.5 8.4 66-4 125.7-33.2 159.6-15.5 18-35 27.8-56.8 28.4 0 0-2.4 0.6-3.2 1.6-1.1 1.4-2.4 6.3-0.7 16.1 12.6 31.1 27.5 62 44.4 91.8 18.4 32.5 39 63.6 61.2 92.5 0.2 0.3 0.5 0.5 0.7 0.8 3.8 4.3 6.4 4.3 7.6 4.3 4.3 0 9.5-2.7 12.6-4.7 14.6-19.9 38.6-30.8 68.4-30.8 40 0 87.7 19.5 130.8 53.4 79.1 62.3 111.6 146.1 82.7 199-2.6 4.7-2.8 5.2-5.4 9.8-19.2 29.4-41.8 54.9-70.8 71.5-27.1 15.5-57.9 23.4-91.4 23.4l0 0C502.9 956.8 344.4 833.7 240.8 650.5zM560.7 661.5c-1.3 2.1-3 4-4.8 5.7-2.2 1.9-22 18.4-47.5 18.4-16.1 0-30.8-6.4-42.7-18.5-1.3-1.1-2.5-2.4-3.6-3.8-24.4-31.5-47-65.4-67.1-100.8-18.4-32.5-34.6-66.2-48.2-100.1-0.6-1.4-1-2.8-1.3-4.3-5.1-24.9-1.6-45.1 10.5-60 15.8-19.6 39.4-20.3 41.6-20.3 2.5-0.1 10.3-0.2 19.4-10.8 19.4-22.6 27.8-69.9 21.4-120.5-9.7-76.5-49.9-133.6-79.7-133.6-1.2 0-2.3 0.2-3.5 0.5-2 0.4-4.1 0.5-6.2 0.4-28.4-1.7-54.4 3.9-76.4 16.4-109.8 62.7-104.2 289.7 12.2 495.5C378.1 791 522.2 906.5 635.2 906.5c24.7 0 47-5.6 66.5-16.7 21.4-12.3 41.3-33.2 54.6-56.2 1.1-1.9 2.6-4.3 4.6-8.2 13.3-25-12.7-86.2-71.9-132.8C655 666 617.8 650 589.3 650 579.5 650 566.6 652 560.7 661.5zM664 480.2c-13.8-2.5-22.9-15.7-20.4-29.5 1.8-9.9-0.3-19.8-6-28-5.7-8.2-14.2-13.8-24.1-15.6-13.8-2.5-22.9-15.7-20.4-29.5 2.5-13.8 15.7-22.9 29.5-20.4 23.2 4.2 43.3 17.3 56.7 36.7 13.4 19.4 18.4 42.9 14.2 66-2.2 12.2-12.9 20.8-24.9 20.8C667.1 480.6 665.5 480.5 664 480.2zM749.7 478.4c-13.8-2.5-22.9-15.7-20.4-29.5 10.4-56.5-27.2-111-83.7-121.3-13.8-2.5-22.9-15.7-20.4-29.5 2.5-13.8 15.8-22.9 29.5-20.4C738.9 293 794.7 373.9 779.3 458c-2.2 12.2-12.9 20.8-24.9 20.8C752.8 478.8 751.3 478.7 749.7 478.4zM848 506.1c-13.8-2.5-22.9-15.8-20.4-29.5C838 420 825.7 362.7 793 315.4c-32.7-47.3-81.9-79.1-138.4-89.5-13.8-2.5-22.9-15.7-20.4-29.5 2.5-13.8 15.8-22.9 29.5-20.4 69.9 12.8 130.7 52.1 171.1 110.6 40.4 58.5 55.6 129.2 42.7 199.2-2.2 12.2-12.9 20.8-24.9 20.8C851.1 506.5 849.5 506.4 848 506.1z" ></path></g>
  </svg>
</template>
<script>
const Phone = {
  props: {
    height: {
      type: [String, Number],
      default: 24
    },
    width: {
      type: [String, Number],
      default: 24
    },
    color: {
      type: String,
      default: '#000'
    }
  }
}

export default Phone;
</script>

**Comment by medz** [comment]
你的 template 内容呢？而且 回复的时候注意使用 **markdown** 哟，否则阅读很困难。

**Comment by 1459416736** [comment]
<template>
    <svg class="icon" viewBox="0 0 24 24" :height="height" :width="width" :fill="color" style="display: inherit;" >
    <g><path d="M240.8 650.5c-134.2-237.4-131.3-485.2 6.6-564 29.8-17 64.1-24.8 101.4-23.1 2.8-0.4 5.6-0.7 8.5-0.8 0.2 0 1.5 0 1.7 0 60.7 0 116.2 76.3 129.1 177.5 8.4 66-4 125.7-33.2 159.6-15.5 18-35 27.8-56.8 28.4 0 0-2.4 0.6-3.2 1.6-1.1 1.4-2.4 6.3-0.7 16.1 12.6 31.1 27.5 62 44.4 91.8 18.4 32.5 39 63.6 61.2 92.5 0.2 0.3 0.5 0.5 0.7 0.8 3.8 4.3 6.4 4.3 7.6 4.3 4.3 0 9.5-2.7 12.6-4.7 14.6-19.9 38.6-30.8 68.4-30.8 40 0 87.7 19.5 130.8 53.4 79.1 62.3 111.6 146.1 82.7 199-2.6 4.7-2.8 5.2-5.4 9.8-19.2 29.4-41.8 54.9-70.8 71.5-27.1 15.5-57.9 23.4-91.4 23.4l0 0C502.9 956.8 344.4 833.7 240.8 650.5zM560.7 661.5c-1.3 2.1-3 4-4.8 5.7-2.2 1.9-22 18.4-47.5 18.4-16.1 0-30.8-6.4-42.7-18.5-1.3-1.1-2.5-2.4-3.6-3.8-24.4-31.5-47-65.4-67.1-100.8-18.4-32.5-34.6-66.2-48.2-100.1-0.6-1.4-1-2.8-1.3-4.3-5.1-24.9-1.6-45.1 10.5-60 15.8-19.6 39.4-20.3 41.6-20.3 2.5-0.1 10.3-0.2 19.4-10.8 19.4-22.6 27.8-69.9 21.4-120.5-9.7-76.5-49.9-133.6-79.7-133.6-1.2 0-2.3 0.2-3.5 0.5-2 0.4-4.1 0.5-6.2 0.4-28.4-1.7-54.4 3.9-76.4 16.4-109.8 62.7-104.2 289.7 12.2 495.5C378.1 791 522.2 906.5 635.2 906.5c24.7 0 47-5.6 66.5-16.7 21.4-12.3 41.3-33.2 54.6-56.2 1.1-1.9 2.6-4.3 4.6-8.2 13.3-25-12.7-86.2-71.9-132.8C655 666 617.8 650 589.3 650 579.5 650 566.6 652 560.7 661.5zM664 480.2c-13.8-2.5-22.9-15.7-20.4-29.5 1.8-9.9-0.3-19.8-6-28-5.7-8.2-14.2-13.8-24.1-15.6-13.8-2.5-22.9-15.7-20.4-29.5 2.5-13.8 15.7-22.9 29.5-20.4 23.2 4.2 43.3 17.3 56.7 36.7 13.4 19.4 18.4 42.9 14.2 66-2.2 12.2-12.9 20.8-24.9 20.8C667.1 480.6 665.5 480.5 664 480.2zM749.7 478.4c-13.8-2.5-22.9-15.7-20.4-29.5 10.4-56.5-27.2-111-83.7-121.3-13.8-2.5-22.9-15.7-20.4-29.5 2.5-13.8 15.8-22.9 29.5-20.4C738.9 293 794.7 373.9 779.3 458c-2.2 12.2-12.9 20.8-24.9 20.8C752.8 478.8 751.3 478.7 749.7 478.4zM848 506.1c-13.8-2.5-22.9-15.8-20.4-29.5C838 420 825.7 362.7 793 315.4c-32.7-47.3-81.9-79.1-138.4-89.5-13.8-2.5-22.9-15.7-20.4-29.5 2.5-13.8 15.8-22.9 29.5-20.4 69.9 12.8 130.7 52.1 171.1 110.6 40.4 58.5 55.6 129.2 42.7 199.2-2.2 12.2-12.9 20.8-24.9 20.8C851.1 506.5 849.5 506.4 848 506.1z" ></path></g>
  </svg>
    </template>
<pre><code>
<script>
const Phone = {
  props: {
    height: {
      type: [String, Number],
      default: 24
    },
    width: {
      type: [String, Number],
      default: 24
    },
    color: {
      type: String,
      default: '#000'
    }
  }
}

export default Phone;
</script>
</code></pre>

**Comment by JsonLeex** [comment]
将代码中的画布大小 viewBox="0 0 24 24" 替换为 viewBox="0 0 1000 1000"；
还有之后出SVG图，请统一 使用 viewBox="0 0 24 24"的画布。

**Comment by 1459416736** [comment]
@JsonLeex  感谢！照你的说的流程操作已经搞定了。
