### ISSUE TITLE
H5登陆错误

### ISSUE THREAD

**Issue by sucof** [slimkit/plus-component-web#95]
安装完plus-component-web，在mysql中修改用户数据登陆，出现xhr.js:178 POST http://localhost/api/v1/auth 500 (Internal Server Error)错误

**Comment by boxshadow** [comment]
这个错误信息有点太简单了.. 你试着访问一下ts+的根节点  不加/web的URL

**Comment by sucof** [comment]
![image](https://user-images.githubusercontent.com/4755824/27810894-6a293e16-6092-11e7-8397-3d51793ac0ca.png)
这是具体的错误信息，上面的账号密码已经存在数据库

**Comment by lain1936** [comment]
看network那栏 是Controllers\\APIs\\V1\\AuthController.php', 81行使用了未定义变量loginrecord

**Comment by medz** [comment]
已经在 slimkit/thinksns-plus#66 中修复。请进入 plus 目录执行 `git pull` 拉取最新代码，感谢。
